### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by Misio12320** [CoolLord22/OtherDrops#48]
Every gameplay this same error and isn't it crashing me my server? When will release spigot version? 1
- *snipped for not using pastebin* -

**Comment by Misio12320** [comment]
https://mclo.gs/XK148PQ here is more, when will release spigot version??? How long can wait does I need give 2 stars maybe please?

**Comment by CoolLord22** [comment]
First of all, you didn’t follow the correct format for reporting bugs. 
Second of all, this issue has been reported at least 2 other times and has been marked as fixed in the beta release. 
Third of all, you’re showing really great character by threatening to rate plugins with bad reviews to get an answer, which I’ve already said 15 times in the overview to not do. 

Lastly, if you want the fixed version, you can join our Discord server and download it there. I can’t release it on spigot yet because there are other issues that need to be solved with it first. Thank you for using OtherDrops

**Comment by Misio12320** [comment]
Yes of course wait 5 years for release 1 update congrats

**Comment by Misio12320** [comment]
Yes. Nice try trying to attack my mental state again... I did not wanted to surrender and give you win but I didn't look about that all... I wont enter on spigot/discord for my past which done me to mental state suicide so... May be sorry but I got upset cause '' friend '' not friend 'cousin' which also i thank him too for this suicide mental state hę was playing minecraft and got crash and he spam me why server crash etc so... Every my game play i have this so i came here and wanted to fix the error cause waiting long time for this update and nothing new...

**Comment by Misio12320** [comment]
Wtf and dislike. You suck not really just for 'say' this word to let

**Comment by CoolLord22** [comment]
I’ve never been more confused but I never attached your mental state and I’m sorry you went through tough times. If you would’ve just paid attention you would realize it’s already been fixed. There’s no need to threaten us developers with a 2 star rating. That’s why I disliked. Your comment about a 5 year wait is completely irrelevant because I haven’t even been developing OtherDrops for a year yet. Anyhow, please keep the github tickets relevant to OtherDrops and bugs you experience with it.
