### ISSUE TITLE
items appear in the inventory

### ISSUE THREAD

**Issue by ElgariaProject** [CoolLord22/OtherDrops#9]
Its not really an issue,I am asking for options for automatic "teleportation" of items to equipment after digging blocks

**Comment by CoolLord22** [comment]
I presume if the inventory is full the item should still drop on the ground?

**Comment by CoolLord22** [comment]
I've tried figuring out how to do this, but I can't find any way to. The problem is, the plugin drops it based on the location where the result happened. It doesn't check for what player or entity was triggering the drop. This raises another issue, if the event was triggered by another entity then there's no player to give the item to.

**Comment by CoolLord22** [comment]
I have a preliminary version ready for testing for this feature request. What is the best way to send you a file? Would you be able to join our Discord server and receive the beta build there?
